language: cpp
jobs:
  include:
    - os: linux
      dist: xenial
      compiler: clang
    - os: linux
      dist: xenial
      compiler: gcc
    - os: linux
      dist: bionic
      compiler: gcc
    - os: osx
      osx_image: xcode10.2
      compiler: clang

addons:
  apt:
    packages:
      - ccache
      - python3-pip
      - doxygen
      - graphviz
  homebrew:
    packages:
      - xz
      - ccache
      - python3

cache:
  - pip
  - ccache
  - directories:
      - $HOME/Library/Caches/Homebrew
before_install:
  - sudo pip3 install --upgrade pip wheel setuptools jinja2
  - sudo pip3 install --upgrade conan
  - conan --version
  - conan user
  - conan remote add worldforge https://api.bintray.com/conan/worldforge/worldforge-conan
script:
  - mkdir build && cd build
  - conan profile new default --detect
  - |
    if [[ "$TRAVIS_OS_NAME" != "osx" && "$CXX" != "clang++" ]]; then
      conan profile update settings.compiler.libcxx=libstdc++11 default
    fi
  - conan install ../tools/conan -pr default --build=missing
  - cmake -DBUILD_SHARED_LIBS=OFF ..
  - make || travis_terminate 1
  - make check || travis_terminate 1
  #  - if [ "$TRAVIS_OS_NAME" != "osx" -a "$CC" == "gcc" ]; then make dox; fi
  - |
    if [[ x"$CONAN_PASSWORD" != "x" && x"$CONAN_LOGIN_USERNAME" != "x" ]]; then
      echo "Creating and uploading Conan artifacts"
      conan user -p $CONAN_PASSWORD -r worldforge $CONAN_LOGIN_USERNAME
      conan remove -f libwfut/*
      conan create ../tools/conan worldforge/testing -pr default --build outdated
      conan upload "libwfut/*@worldforge/testing" -r worldforge -c --all
    fi
